name: Deployment QA

on:
  pull_request:
    branches: [ "main" ]

env:
  ROLLBACK_FOLDER: "rollback_$(date +%Y_%m_%d_%H_%M_%S)"

jobs:

  deploy-to-qa:
    name: Deploy
    runs-on: ubuntu-latest
    needs: call_get_last_commit_in_pr
    if: ${{ !contains(needs.call_get_last_commit_in_pr.outputs.lastcommit, '[skip DeploymentQA]') }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Rename dist to rollback ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_QA }}
          username: ${{ secrets.SERVER_USER_QA }}
          key: ${{ secrets.SERVER_SSH_KEY_QA }}
          port: ${{ secrets.SERVER_SSH_PORT_QA }}
          script: |
            mv -f "/var/www/qa-web/test/to_rename /var/www/qa-web/test/$ROLLBACK_FOLDER"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_QA }}
          SLACK_USERNAME: rtCamp
          SLACK_TITLE: Deploy to QA
          SLACK_MESSAGE: "rollback folder => $ROLLBACK_FOLDER"
          SLACK_ICON: https://github.com/rtCamp.png?size=48

      # - name: Copy file via SSH
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SERVER_HOST_QA }}
      #     username: ${{ secrets.SERVER_USER_QA }}
      #     port: ${{ secrets.SERVER_SSH_PORT_QA }}
      #     key: ${{ secrets.SERVER_SSH_KEY_QA }}
      #     rm: true
      #     source: "./build/*.*"
      #     target: "/var/www/ob-qa"