name: Deployment QA

on:
  pull_request:
    branches: [ "main" ]

jobs:


  job_generate_rollback_folder_name:
    name: Generate rollback folder name
    runs-on: ubuntu-latest
    outputs:
      ROLLBACK_FOLDER_NAME: ${{ steps.generate_rollback_folder_name.outputs }}

    steps:
      - name: gemerate name folder
        id: generate_rollback_folder_name
        run: echo "ROLLBACK_FOLDER_NAME=rollback_$(date +%Y_%m_%d_%H_%M_%S)" >> "$GITHUB_OUTPUT"

  deploy-to-qa:
    name: Deploy
    runs-on: ubuntu-latest
    needs: job_generate_rollback_folder_name

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Rename dist to rollback ssh
        run: echo "${{ needs.job_generate_rollback_folder_name.outputs.ROLLBACK_FOLDER_NAME }}"
        # with:
        #   host: ${{ secrets.SERVER_HOST_QA }}
        #   username: ${{ secrets.SERVER_USER_QA }}
        #   key: ${{ secrets.SERVER_SSH_KEY_QA }}
        #   port: ${{ secrets.SERVER_SSH_PORT_QA }}
        #   script: |
        #     echo "$ROLLBACK_FOLDER"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_QA }}
          SLACK_USERNAME: rtCamp
          SLACK_TITLE: Deploy to QA
          SLACK_MESSAGE: rollback folder => ${{ needs.job_generate_rollback_folder_name.outputs.ROLLBACK_FOLDER_NAME }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48