name: Main flow completed

on:
  pull_request:
    branches: [ "main" ]

jobs:

  call_get_last_commit_in_pr:
    uses: ./.github/workflows/wf_call_get_last_commit_in_pt.yml

  call_unity_testing:
    needs: call_get_last_commit_in_pr
    if: ${{ !contains(needs.call_get_last_commit_in_pr.outputs.lastcommit, '[skip testing]') }}
    uses: ./.github/workflows/wf_call_unity_testing.yml

  call_deployment:
    needs: [call_get_last_commit_in_pr, call_unity_testing]
    if: ${{ !contains(needs.call_get_last_commit_in_pr.outputs.lastcommit, '[skip deployment]') }}
    uses: ./.github/workflows/wf_call_deploy.yml
    with:
      SERVER_HOST_QA: "${{ secrets.SERVER_SSH_PORT_QA }}"
    #   SERVER_USER_QA: ${{ secrets.SERVER_USER_QA }}
    #   SERVER_SSH_KEY_QA: ${{ secrets.SERVER_SSH_KEY_QA }}
    #   SERVER_SSH_PORT_QA: ${{ secrets.SERVER_SSH_PORT_QA }}
    #   SERVER_SSH_PORT_QA: ${{ secrets.SERVER_SSH_PORT_QA }}
