name: TestBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:

  call_get_last_commit_in_pr:
    uses: ./.github/workflows/wf_call_get_last_commit_in_pt.yml.yml

  build_app:
    name: Build APP
    runs-on: ubuntu-latest
    needs: callWorkflowCheckSkipFlags
    if: ${{ !contains(needs.callWorkflowCheckSkipFlags.outputs.lastcommit, '[skip TestBuild]') }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

