name: Main flow completed

on:
  pull_request:
    branches: [ "main" ]

jobs:

  call_get_last_commit_in_pr:
    uses: ./.github/workflows/wf_call_get_last_commit_in_pt.yml

  call_unity_testing:
    needs: call_get_last_commit_in_pr
    if: ${{ !contains(needs.call_get_last_commit_in_pr.outputs.lastcommit, '[skip testing]') }}
    uses: ./.github/workflows/wf_call_unity_testing.yml

  call_deployment:
    needs: [call_get_last_commit_in_pr, call_unity_testing]
    if: ${{ !contains(needs.call_get_last_commit_in_pr.outputs.lastcommit, '[skip deployment]') }}
    uses: ./.github/workflows/wf_call_deploy.yml
    with:
      PATH: "/var/www/qa-web/test"
    secrets:
      SERVER_HOST_QA: "${{ secrets.SERVER_HOST_QA }}"
      SERVER_USER_QA: ${{ secrets.SERVER_USER_QA }}
      SERVER_SSH_KEY_QA: ${{ secrets.SERVER_SSH_KEY_QA }}
      SERVER_SSH_PORT_QA: ${{ secrets.SERVER_SSH_PORT_QA }}

  call_slack_notification:
    needs: call_deployment
    uses: ./.github/workflows/wf_call_slack_notification.yml
    with:
      title: "Deploy to QA"
      message: "rollback folder: ${{needs.call_deployment.outputs.toRollback}}"
      color: ${{ needs.jobs.call_slack_notification.status }}
    secrets:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_QA }}

  debug:
    needs: [call_get_last_commit_in_pr, call_unity_testing, call_deployment]
    if: ${{ failure() }}
    uses: ./.github/workflows/wf_call_slack_notification.yml
    with:
      title: "Main flow completed :: failure"
      message: "ERROR: job.steps.bad.status ddd"
      username: "JobsError"
      icon: "https://img.icons8.com/arcade/100/close-window.png"
      color: 'failure'
    secrets:
      WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_QA }}
