name: Testings
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}

    steps:
      - name: Get repo
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  build_app:
    name: Build APP
    runs-on: ubuntu-latest
    needs: check_skip_flags
    if: ${{ !contains(needs.check_skip_flags.outputs.head-commit-message, '#skip testing') }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, test
        run: |
          npm install
          npm run test

