name: Get Last Commit text
on:
  workflow_call:
    outputs:
      lastcommit:
        description: "last commit text"
        value: ${{ jobs.get_last_commit_in_pt.outputs.head-commit-message }}

jobs:
  get_last_commit_in_pt:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.lastcommit }}

    steps:
      - name: Get repo
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "lastcommit=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
