name: deploy

on:
  workflow_call:
    inputs:
      input_SERVER_HOST_QA:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: echo result
        id: generate_rollback_folder_name
        run: echo "resulkt ${{ inputs.input_SERVER_HOST_QA }}"