name: deploy

on:
  workflow_call:
    inputs:
      PATH:
        required: true
        type: string
      CURRENT_APP_FOLDER_NAME:
        description: 'Folder con la app actual'
        default: 'dist'
        required: false
        type: string
    outputs:
      toRollback:
        description: "folder To Rollback"
        value: ${{ jobs.job_generate_rollback_folder_name.outputs.FOLDER_NAME }}
    secrets:
      SERVER_HOST_QA:
        required: true
      SERVER_USER_QA:
        required: true
      SERVER_SSH_KEY_QA:
        required: true
      SERVER_SSH_PORT_QA:
        required: true

jobs:

  job_generate_rollback_folder_name:
    name: Generate rollback folder name
    runs-on: ubuntu-latest
    outputs:
      FOLDER_NAME: ${{ steps.generate_rollback_folder_name.outputs.rollbackName }}

    steps:
      - name: gemerate name folder
        id: generate_rollback_folder_name
        run: echo "rollbackName=rollback_$(date +%Y_%m_%d_%H_%M_%S)" >> "$GITHUB_OUTPUT"
        run: echo ${{ inputs.PATH }}/${{ inputs.CURRENT_APP_FOLDER_NAME }} ${{ inputs.PATH }}/${{ needs.job_generate_rollback_folder_name.outputs.FOLDER_NAME }}


  # deploy-to-qa:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: job_generate_rollback_folder_name

  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   steps:
  #     - name: Rename dist to rollback ssh
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST_QA }}
  #         username: ${{ secrets.SERVER_USER_QA }}
  #         key: ${{ secrets.SERVER_SSH_KEY_QA }}
  #         port: ${{ secrets.SERVER_SSH_PORT_QA }}
  #         script: |
  #           mv -f ${{ inputs.PATH }}/${{ inputs.CURRENT_APP_FOLDER_NAME }} ${{ inputs.PATH }}/${{ needs.job_generate_rollback_folder_name.outputs.FOLDER_NAME }}
